Complete the image if catkin build fails partially.

diff --git a/scripts/setup_catkin_workspace b/scripts/setup_catkin_workspace
--- a/scripts/setup_catkin_workspace
+++ b/scripts/setup_catkin_workspace
@@ -88,4 +88,6 @@ cd "${ws}"
 catkin init
 catkin config --extend "${extend}"
 catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release
-catkin build -c
+if ! catkin build -c; then
+    echo 'ERROR: Catkin build incomplete!'
+fi
